### ISSUE TITLE
Error when terminating instance with attached network interface

### ISSUE THREAD

**Issue by mathisve** [mathisve/gravitonctl#1]
I attached a network interface to this instance manually.
This caused `gravitonctl termiante` to fail because the network interface is dependent on the instance.

There should be a check in place to see if the instance has any dependent resources

```
mathis@MacBook-Pro ~ % gravitonctl terminate instance
INFO[0000] Terminating: i-0546d514990d2711f
panic: DependencyViolation: resource sg-0e49b3c51acab7a5a has a dependent object
	status code: 400, request id: 796b5740-b055-4ad9-9aed-b950c8493544

goroutine 1 [running]:
gravitonctl/cmd.glob..func5(0x105334400, {0x1400006def0, 0x1, 0x1})
	/Users/mathis/git/gravitonctl/cmd/terminate.go:26 +0xd8
github.com/spf13/cobra.(*Command).execute(0x105334400, {0x1400006dec0, 0x1, 0x1})
	/Users/mathis/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14000330000)
	/Users/mathis/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mathis/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
gravitonctl/cmd.Execute()
	/Users/mathis/git/gravitonctl/cmd/root.go:21 +0xcc
main.main()
	/Users/mathis/git/gravitonctl/main.go:12 +0x20
```

**Comment by mathisve** [comment]
start an instance
```➜  gravitonctl git:(master) ✗ ./gravitonctl start delete-ni-test
INFO[0005] Instance launched: i-01ea29d14ca4310a6
INFO[0005] connecting to instance: delete-ni-test
INFO[0008] 3.70.252.255

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
```
manually add network interface (eth1)

```
[ec2-user@ip-172-31-38-16 ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.31.38.16  netmask 255.255.240.0  broadcast 172.31.47.255
        inet6 fe80::498:85ff:fe68:1eea  prefixlen 64  scopeid 0x20<link>
        ether 06:98:85:68:1e:ea  txqueuelen 1000  (Ethernet)
        RX packets 57273  bytes 80024027 (76.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3711  bytes 262804 (256.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.31.40.169  netmask 255.255.240.0  broadcast 172.31.47.255
        inet6 fe80::4dd:18ff:fe5a:71f0  prefixlen 64  scopeid 0x20<link>
        ether 06:dd:18:5a:71:f0  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 1152 (1.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 1526 (1.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 24  bytes 1944 (1.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24  bytes 1944 (1.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
delete the instance
```
➜  gravitonctl git:(master) ✗ ./gravitonctl terminate delete-ni-test
INFO[0000] Detaching network interface: eni-0a009f8c17892b87a
WARN[0022] Network interface: eni-0a009f8c17892b87a detached, but not deleted!
INFO[0022] Terminating: i-01ea29d14ca4310a6
INFO[0068] Deleting sg: sg-0268b4706beeaf19e
```
network interface is detached but not deleted!
